apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: demoyuw/flask-api:master
        ports:
        - containerPort: 10009
